### ISSUE TITLE
Universal Type Client 5+6 issues

### ISSUE THREAD

**Issue by pexner** [autopkg/jessepeterson-recipes#23]
There are new versions of UTC out and the receipt for UTC6 errors with 
"No matching filename found".
Looks like there's no URL to download the UTC6 inside the munki receipt. (I'm not a coder, but it looks like it's missing.)

The UTC5 receipe errors with:
"Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value."

There were some changes in the Extensis a3 server, please look at your personal messages in Slack.

**Comment by jessepeterson** [comment]
Hi @pexner! Thanks for submitting. UTC6 was fixed with `511ac48d639f2731311067093f41e79aa9d80e0f`. UTC5 as distributed by Extensis is broken: it has an invalid code signature. One just needs to set the `-k DISABLE_CODE_SIGNATURE_VERIFICATION=1` when running autopkg, or sets that in an `Input` variable in an override for it.
